config/routes.rb
Rails.application.routes.draw do
  namespace :label_maker, path: '' do
    resources :case_filters, only: [:index, :show]

    resources :labels, only: [:create, :index, :new]

    resources :cases, only: [] do
      post :assign, on: :member
    end
  end

  get 'home', to: 'static_pages#home'
  root to: 'label_maker/case_filters#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/label_maker/case_filters_controller.rb
class LabelMaker::CaseFiltersController < ApplicationController
  def index
    @case_filters = LabelMaker::CaseFilter.all
  end

  def show
    @case_filter = LabelMaker::CaseFilter.find(params[:id])
    @labels = LabelMaker::Label.all
  end
end

app/controllers/label_maker/cases_controller.rb
module LabelMaker
  class CasesController < ApplicationController
    def assign
      desk_case = LabelMaker::Case.find(params[:id])
      desk_case.assign_label(params[:label_id])
      redirect_to :back
    end
  end
end

app/controllers/label_maker/labels_controller.rb
module LabelMaker
  class LabelsController < ApplicationController
    def create
      LabelMaker::Label.create(label_params)
      flash[:notice] = t('text.controllers.labels.create.success')
      redirect_to label_maker_labels_path
    end

    def index
      @labels = LabelMaker::Label.all
    end

    def new
      @label = LabelMaker::Label.new
    end

    private
    def label_params
      params.require(:label_maker_label).permit(:name)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/label_maker/case_filters/_case_filter.html.erb
<li>
  <%= link_to case_filter.name, label_maker_case_filter_path(case_filter) %>
</li>

app/views/label_maker/case_filters/index.html.erb
<div class="columns large-12">
  <h3><%= t('text.controllers.case_filters.index') %></h3>
  <% if @case_filters.any? %>
    <ol>
      <%= render @case_filters %>
    </ol>
  <% else %>
    <p><%= t('text.models.case_filter.none') %></p>
  <% end %>
</div>

app/views/label_maker/case_filters/show.html.erb
<div class='columns large-12'>
  <h3><%= @case_filter.name %></h3>
  <% if @case_filter.cases.any? %>
    <div class='cases'>
      <%= render partial: 'label_maker/cases/desk_case',
                 collection: @case_filter.cases %>
    </div>
  <% else %>
    <p><%= t('text.models.case.none') %></p>
  <% end %>
</div>

app/views/label_maker/cases/_desk_case.html.erb
<%= div_for desk_case, class: 'panel radius' do %>
  <h4><%= desk_case.subject %></h4>

  <p><%= desk_case.blurb %>&hellip;</p>

  <%= form_tag assign_label_maker_case_path(desk_case) do %>
    <%= select_tag :label_id,
                   options_from_collection_for_select(@labels, :id, :name),
                   class: 'inline' %>
    <%= submit_tag t('forms.buttons.assign'), class: 'button round tiny' %>
  <% end %>

  <div class='clearfix'>
    <%= render desk_case.labels %>
  </div>
<% end %>

app/views/label_maker/labels/_label.html.erb
<%= content_tag :i, label.name, class: "label radius #{label.color}" %>

app/views/label_maker/labels/index.html.erb
<div class="columns large-12">
  <h3><%= t('text.controllers.labels.index') %></h3>
  <% if @labels.any? %>
    <div class='clearfix'>
      <%= render @labels %>
    </div>
  <% else %>
    <p><%= t('text.models.label.none') %></p>
  <% end %>

  <%= link_to t('links.controllers.labels.new'),
              new_label_maker_label_path,
              class: 'button small'%>
</div>

app/views/label_maker/labels/new.html.erb
<div class='columns large-12'>
  <h3><%= t('text.controllers.labels.new') %></h3>

  <%= form_for @label do |f| %>
    <div class='field'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class='actions'>
      <%= f.submit t('forms.buttons.submit'), class: 'button small round' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "LabelMaker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class='row'>
      <nav id='main_nav' class='columns large-12'>
        <%= link_to t('links.controllers.case_filters.index'),
                    label_maker_case_filters_path %> |
        <%= link_to t('links.controllers.labels.index'),
                    label_maker_labels_path %>
      </nav>
    </header>

    <section class='row'>
      <% flash.each do |type, msg| %>
        <div class='columns large-12'>
          <div data-alert class='alert-box <%= type %> radius'>
            <%= msg %>
            <a href='#' class='close'>&times;</a>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </section>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class='columns large-12'>
  <p>This page is here so New Relic can ping the site and not kill my Desk.com API request limit<p>
</div>